version: '3.3'

services:

  rabbitmq:
    image: docker.io/rabbitmq:3.9-management
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: db
    ports:
      - "1433:1433" # Publishes the port to docker host in order to access db from vscode extension. 
    environment:
      - SA_PASSWORD=Student1
      - ACCEPT_EULA=Y
    networks:
      - uuidmasterapi
    volumes:
      - db_data:/var/opt/mssql
  api:
    depends_on:
      - db
    build:
      context: ./uuid
      dockerfile: Dockerfile
    ports: # replace by expose
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - uuidmasterapi
      
  mysqldb:
    image: mysql/mysql-server:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbpasswd
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: suitecrm-db
    networks:
      - crmNetwork
    volumes:
      - 'suitecrm-db:/var/lib/mysql'
    ports:
      - '3306:3306'

  suitecrm:
    depends_on:
      - crm-mysqldb
    image: docker.io/thaso/ipwt22-suitecrm:latest
    container_name: suitecrm
    restart: unless-stopped
    environment:
      APACHE_HTTP_PORT_NUMBER: '8080'
      APACHE_HTTPS_PORT_NUMBER: '8443'
      SUITECRM_USERNAME: user
      SUITECRM_PASSWORD: bitnami
      SUITECRM_EMAIL: user@example.com
      SUITECRM_SKIP_BOOTSTRAP: 'no'
      SUITECRM_HOST: localhost
      SUITECRM_ENABLE_HTTPS: 'no'
      SUITECRM_EXTERNAL_HTTP_PORT_NUMBER: '80'
      SUITECRM_EXTERNAL_HTTPS_PORT_NUMBER: '443'
      SUITECRM_DATABASE_HOST: mysqldb # define the address/hostname of the mysql server eg mysql container name
      SUITECRM_DATABASE_PORT_NUMBER: '3306'
      SUITECRM_DATABASE_NAME: suitecrm-db
      SUITECRM_DATABASE_USER: root # this is the root user to login on startup
      SUITECRM_DATABASE_PASSWORD: mypassword
      ALLOW_EMPTY_PASSWORD: 'yes'
      #MYSQL_CLIENT_FLAVOR: mysql
      #MYSQL_CLIENT_DATABASE_HOST: mysqldb
      #MYSQL_CLIENT_DATABASE_PORT_NUMBER: '3306'
    networks:
      - crmNetwork
    ports:
      - '80:8080'
      - '443:8443'

  crm-api:
    depends_on:
      - rabbitmq
    build:
        context: ./crm
        dockerfile: Dockerfile
    # image: docker.io/thaso/suitecrm-api:latest
    container_name: crm-api
    restart: unless-stopped
    networks:
      - crmNetwork
      - rabbitmq
      - uuidmasterapi
    ports:
      - '5172:80'

  planning:
    depends_on:
      - crm-api
    build:
        context: ./planning
        dockerfile: Dockerfile
    container_name: planning-api
    restart: unless-stopped
    networks:
      - rabbitmq
      - planning
      - uuidmasterapi
    ports:
      - '6002:80'
      - '6003:443'

networks:
    crmNetwork:
        name: crmNetwork
        driver: bridge
    #frontend:
    #    name: frontend
    #    driver: bridge
    planning:
        name: planning
        driver: bridge
    rabbitmq:
        name: rabbitmq
        driver: bridge
    uuidmasterapi:
        name: uuidmasterap
        driver: bridge

volumes: # add persistent data even if container is removed
    suitecrm-db:
        driver: local
    
    rabbitmq_data: {
    name: rabbitmq_data
    }
    db_data: {}